name: Commit
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@main

      - name: Dockerhub
        uses: comworkio/action-kaniko@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: comworkio/kaniko
          cache: true
          cache_registry: comworkio/cache
