name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notes:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Notary Action
        uses: docker://comworkio/release-notary@sha256:b77e86ce9ce4b0c8774cdb3b807b756d1d6139d73aca74388560250de259be4e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dockerhub
        uses: comworkio/action-kaniko@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: comworkio/kaniko
          cache: true
          cache_registry: comworkio/cache
